# Generated by Django 5.2.6 on 2025-09-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=200)),
                ('actor1_name', models.CharField(max_length=100)),
                ('actor2_name', models.CharField(blank=True, max_length=100)),
                ('director_name', models.CharField(max_length=100)),
                ('movie_genre', models.CharField(max_length=50)),
                ('release_year', models.PositiveIntegerField()),
            ],
        ),
    ]
