# Generated by Django 5.2.6 on 2025-09-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='movie_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
