# Generated by Django 5.2.6 on 2025-09-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_alter_video_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='release_year',
            field=models.CharField(max_length=4),
        ),
    ]
